### ISSUE TITLE
Client App and Server App error

### ISSUE THREAD

**Issue by juber-ivre** [iotivity/iotivity-lite#14]
Foolowing the instructions I'm getting the error below towards the very end.

otgc-linux/src/main/java/org/openconnectivity/otgc/utils/util/DialogHelper.java:[22,20] package javafx.scene does not exist

On the Server App I'm getting the following error

make: *** No rule to make target '../../apps/device_builder_server.c', needed by 'device_builder_server'.  Stop.

I'm on Ubuntu 20.04. Any suggestions?

**Comment by WAvdBeek** [comment]
which make command has been run?
just looking at the make file in master (port/linux) there is no compile target called device_builder_server

**Comment by WAvdBeek** [comment]
when using the device_builder device chain, this error might happen when gen.sh is not run
The gen.sh step creates the device_builder_server
