### ISSUE TITLE
[Regression][CTT tests]Fails of tests 1.2.2, 1.2.6, 1.4.8, 1.4.9 - incorrect empty fields

### ISSUE THREAD

**Issue by SiMet** [iotivity/iotivity-lite#195]
Hi all,

After commit a3a75a532e073da44dd15dbf34c5a99ffdd5eef8 we found regression in testing with the CTT:
[2022-02-23-01-50-11_Server Certification_retest.zip](https://github.com/iotivity/iotivity-lite/files/8123310/2022-02-23-01-50-11_Server.Certification_retest.zip)

There are issues:
1.2.2 - empty SID in response from CoApCloundConf does not match pattern: ^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$ from schema
1.2.6 - empty SID in response from CoApCloundConf does not match pattern: ^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$ from schema

1.4.8 value of property 'cis' is empty string while expected 00000000-0000-0000-0000-000000000000
1.4.9 value of property 'cis' is empty string while expected 00000000-0000-0000-0000-000000000000

**Comment by SiMet** [comment]
FYI @Oxymoron79 @WAvdBeek @o-andrieiev

**Comment by WAvdBeek** [comment]
Josef, since this is cloud related, can you take a look?

**Comment by SiMet** [comment]
After fix #199 issues from tests 1.2.2 and 1.2.6 gone.

However, there is still issue in tests 1.4.8 and 1.4.9 which require that 'cis' will be coaps+tcp://127.0.0.1

Please see Table 13 – Default values for CoAPCloudConf Resource of "OCF Device to Cloud Services Specification VERSION 2.2.5" (https://openconnectivity.org/specs/OCF_Device_To_Cloud_Services_Specification_v2.2.5.pdf)


If empty value is valid then CTT scripts need to be updated. If so, please create ticket on bugzilla system
