### ISSUE TITLE
raspberry pi build error 

### ISSUE THREAD

**Issue by city256** [iotivity/iotivity-lite#198]
hi 

Ioticity-lite is installed on raspberry pi, and an error occurs while continuing to run build.sh.

https://iotivity.org/GS_DS/
Even if follow the site above, the following errors occur.

> ../../api/oc_core_res.c: In function ‘oc_core_con_handler_post’:
> ../../api/oc_core_res.c:287:38: error: implicit conversion from ‘oc_locn_t’ to ‘oc_enum_t’ [-Werror=enum-conversion]
>   287 |         oc_resource_tag_locn(device, oc_locn);
>       |                                      ^~~~~~~
> cc1: all warnings being treated as errors
> make: *** [Makefile:307: obj/client_server/oc_core_res.o] Error 1

I would appreciate it if you could tell me the solution.

**Comment by Danielius1922** [comment]
Hi @city256, can you please tell me your compiler and its version that you're using?

I think gcc >= 9 has some new diagnostic warnings and having `-Werror` enabled causes compilation failure.
