### ISSUE TITLE
[CTT] Regression in oic.r.softwareupdate resource

### ISSUE THREAD

**Issue by SiMet** [iotivity/iotivity-lite#234]
Hi,

After changes from #229 CTT start failing tests 1.2.3 and 1.7.8.3.

I see that already there rule for schema validation fails.
In schema: https://github.com/openconnectivityfoundation/core-extensions/blob/OCF-v2.2.5/swagger2.0/oic.r.softwareupdate.swagger.json
we see that update should require properties: ["purl", "swupdateaction", "updatetime"] while now it's not.

Change of code or schema is needed.

Please see logs from failing tests: [2022-04-05-00-22-27_Client Certification_retest.zip](https://github.com/iotivity/iotivity-lite/files/8415856/2022-04-05-00-22-27_Client.Certification_retest.zip)

**Comment by SiMet** [comment]
FIY @WAvdBeek

**Comment by Oxymoron79** [comment]
I was looking into the specification for the software update resource (OCF Core Optional Specification, Section 5.3.5) before I proposed #229:
I couldn't conclude from the specification, that the `purl` property needs to be set with a `updateaction` and a `updatetime`. On the contrary, the typical update scenario depicted in Figure 4 shows the setting the `purl` property as a separate `software upgrade initialisation` step.

Also, as the software update shall be able to controlled with the `oic.r.pstat` resource, the `purl` needs to be set before. But as far as I am aware there is no appropriate `updateaction` to only set the `purl`.

Considering this (assuming that my understanding of the specification is correct), I think that the schema needs to be changed.

**Comment by WAvdBeek** [comment]
i am reverting this change.
the spec is not going to change to accomodate this sw change.

**Comment by ondrejtomcik** [comment]
@WAvdBeek could you please look into the schema and flow Martin described based on the spec? I think nobody tested it in real, just wrote a test verifying properties but didn't consider the end-to-end scenario.

**Comment by WAvdBeek** [comment]
no, we are not going to change the spec, the schema is part of the spec and it is being enforced by the CTT.

**Comment by SiMet** [comment]
After revert this issue is solved. From my perspective this ticket could be closed.

**Comment by ondrejtomcik** [comment]
I agree that spec defines the state of art - model as well as workflow and that it needs to be verified by the CTT.

The question is if you could verify our understanding of the spec, and the inconsistency we see there? We are not asking to revert your revert, just help us to understand and make software updates as defined by the OCF usable in real production - either by doing a CR that fixes the spec or guiding us on why we are understanding it wrongly.

**Comment by ondrejtomcik** [comment]
> After revert this issue is solved. From my perspective this ticket could be closed.

Yes. And just another reason why I need to hurry up with CTT automated builds with GitHub. Will continue on this during vacation! :)

**Comment by Oxymoron79** [comment]
> we see that update should require properties: ["purl", "swupdateaction", "updatetime"] while now it's not.

If I update the POST request in #229 to require the `purl` property again, the CTT test would then pass, right?
That should be easy to do.

**Comment by SiMet** [comment]
> > we see that update should require properties: ["purl", "swupdateaction", "updatetime"] while now it's not.
> 
> If I update the POST request in #229 to require the `purl` property again, the CTT test would then pass, right? That should be easy to do.

Please, write me an email marek.szkowron@comarch.com in case you prepare change and like to get tests results.
