### ISSUE TITLE
 About the failure of some CTT test cases

### ISSUE THREAD

**Issue by avpmax** [iotivity/iotivity-lite#279]
I am developing in ESP32 (WROOM-32D) environment.
However, it does not pass some tests of CTT(ver 2102.0).
The failure of the test case is also reproducible in the provided examples.
(simple_server example that generated by build.sh or esp32 port)

**Fail:**
CT1.7.4.7 Credential for onboarding and post-onboarding (D)TLS session establishment
CT1.7.8.11 Implicit Behavior of SVR Properties in Each Device State

**Warning:**
CT1.7.12.5 Verift RFOTM behavior when OTM sequence does not complete

CTT Test case logs are as attached.

I've tried many ways including menuconfig, but still can't get it to work.
What am I missing?
Any advice would be appreciated.

**Test Logs:**
[CT1.7.4.7_testlog.txt](https://github.com/iotivity/iotivity-lite/files/8925312/CT1.7.4.7_testlog.txt)
[CT1.7.8.11_testlog.txt](https://github.com/iotivity/iotivity-lite/files/8925313/CT1.7.8.11_testlog.txt)
[CT1.7.12.5_testlog.txt](https://github.com/iotivity/iotivity-lite/files/8925314/CT1.7.12.5_testlog.txt)

**Comment by jkralik** [comment]
@avpmax Could you please try it with the current master branch? I merged a new version this week that contains some fixes.

**Comment by Danielius1922** [comment]
No response, closing.
