### ISSUE TITLE
Linux network_event_thread get stuck in a loop when unable to find a session socket

### ISSUE THREAD

**Issue by TomCahill** [iotivity/iotivity-lite#401]
The `network_event_thread` seems to get stuck churning out the same event when it's unable to find a open TCP session for it. This loop continues until the process is stopped.

I was able to trigger this when opening a COAPS+TCP from a client which the server ended up closing due to a cert validation error.

```sh
DEBUG: observe.c <coap_remove_observer_by_client:314>: coaps+tcp://192.168.0.77:46234
D: observe.c <coap_remove_observer_by_client:324>: Removed 0 observers
could not find ongoing TCP session for endpoint:coaps+tcp://192.168.0.77:46234
mbedtls_log: /iotivity-lite/deps/mbedtls/library/ssl_tls.c:6276: => free
mbedtls_log: /iotivity-lite/deps/mbedtls/library/ssl_tls.c:6344: <= free
D: oc_tls.c <read_application_data:2474>: oc_tls: In read_application_data
D: oc_tls.c <read_application_data:2476>: oc_tls: read_application_data: Peer not active
D: ipadapter.c <process_events:1128>: processing 1 events
D: tcpsession.c <tcp_receive_message:448>: could not find TCP session socket in fd set
D: ipadapter.c <process_event:1116>: no handler found for event
D: ipadapter.c <process_events:1128>: processing 1 events
D: tcpsession.c <tcp_receive_message:448>: could not find TCP session socket in fd set
D: ipadapter.c <process_event:1116>: no handler found for event
D: ipadapter.c <process_events:1128>: processing 1 events
D: tcpsession.c <tcp_receive_message:448>: could not find TCP session socket in fd set
D: ipadapter.c <process_event:1116>: no handler found for event
...
D: ipadapter.c <process_events:1128>: processing 1 events
D: tcpsession.c <tcp_receive_message:448>: could not find TCP session socket in fd set
D: ipadapter.c <process_event:1116>: no handler found for event
...
```

**Comment by Danielius1922** [comment]
Seems like a leaked file descriptor that wasn't closed...? I can add a log that prints the values of unhandled fds in the fd set(s). I think that all openings of fds are logged. So, if you then replicate it and provide me with a full log dump then I should be able to identify the problematic file descriptor, when it got opened and what happened.

**Comment by TomCahill** [comment]
@Danielius1922 Sorry, I've spotted that you've replied. If you send over any extra log lines that might be useful, I'll throw them in and replicate it.

I've attached a log of the last time I ran into it: [device1.txt](https://github.com/iotivity/iotivity-lite/files/11004034/device1.txt)

**Comment by Danielius1922** [comment]
I've added some logging of file descriptors. However, I think I might've fixed the issue going by the latest log you've sent (https://github.com/iotivity/iotivity-lite/pull/404/files#diff-b3384c6c3c603f2b81c755539bdccd3ca83f127d7775e79f712534d69c7feba0L1012). 
Could you please the branch from https://github.com/iotivity/iotivity-lite/pull/404 ?

**Comment by TomCahill** [comment]
Perfect thanks, tested the branch and this resolves the issue.
