### ISSUE TITLE
The official server app demo can not pass the CTT

### ISSUE THREAD

**Issue by xiao8xiao1** [iotivity/iotivity-lite#41]
we Follow the official website documentation:   https://iotivity.org/getting-started-iotivity-device-simulation ，the topic is “Getting started with IoTivity - Device simulation”。and we do not change any code 。
But when we test the server app with the CTT tool， it failed.
we have try iotivity 2.2.0 with  CTT_2002.5.0 failed
then we try iotivity 2.2.2 with  CTT_2101.0.0  failed
our own porting device report the same problem. 
how to make the official the server app pass the CTT?  we need a a step by step howto document

**Comment by WAvdBeek** [comment]
https://github.com/iotivity/iotivity-lite/wiki/running-CTT-with-a-Device-Builder-generated-server
