### ISSUE TITLE
TLS: closing of TLS peer vs. closing of TCP session

### ISSUE THREAD

**Issue by Danielius1922** [iotivity/iotivity-lite#441]
The IoTivity-lite TLS session consists of the two layers: a TCP session (takes care of the socket belonging to the TLS session) and a TLS peer (takes care of security). 
When a TLS session is closed then first the TLS peer is closed and deallocated (on the main thread) and message is sent to the network thread to stop and deallocate the corresponding TCP session. 

Unfortunately, there is a unhandled race condition when the TLS has been already deallocate, but the message to stop the TCP session hasn't been handled yet. It is possible for the TCP socket in this time window to receive a message and add it to the list of inbound messages waiting to be processed. The situation is illustrated in the log from IoTivity v2.2.5.4:

```text
main thread:
[OC 2023-05-01T19:48:27.180635Z] DEBUG: oc_tls.c:335 <oc_tls_free_peer>: oc_tls: freeing peer(0x55dc17485790)
[OC 2023-05-01T19:48:27.180645Z] DEBUG: oc_pstat.c:109 <print_pstat_dos>: oc_pstat: dos is RFNOP
[OC 2023-05-01T19:48:27.180654Z] DEBUG: observe.c:313 <coap_remove_observer_by_client>: Unregistering observers for client at: 
[OC 2023-05-01T19:48:27.180668Z] DEBUG: observe.c:314 <coap_remove_observer_by_client>: endpoint coaps+tcp://127.0.0.1:40030
[OC 2023-05-01T19:48:27.180747Z] DEBUG: observe.c:324 <coap_remove_observer_by_client>: Removed 0 observers
[OC 2023-05-01T19:48:27.180756Z] DEBUG: transactions.c:278 <coap_free_transactions_by_endpoint>: coap_free_transactions_by_endpoint

network thread:
[OC 2023-05-01T19:48:27.180863Z] DEBUG: ipadapter.c:1129 <process_events>: processing 1 events
[OC 2023-05-01T19:48:27.180880Z] DEBUG: oc_buffer.c:88 <allocate_message>: buffer: allocated message(0x7fdaf0004bd0) from pool(0x7fdaf78c88a0)
[OC 2023-05-01T19:48:27.180917Z] DEBUG: tcpsession.c:468 <tcp_receive_message>: tcp receive session(fd=20)
[OC 2023-05-01T19:48:27.180930Z] DEBUG: tcpsession.c:409 <tcp_session_receive_message>: recv(): 6 bytes.
[OC 2023-05-01T19:48:27.180939Z] DEBUG: oc_tcp.c:96 <oc_tcp_is_valid_header>: TLS header: record type: 21, major 3, minor 3
[OC 2023-05-01T19:48:27.180949Z] DEBUG: tcpsession.c:435 <tcp_session_receive_message>: tcp packet total length : 31 bytes.
[OC 2023-05-01T19:48:27.180960Z] DEBUG: tcpsession.c:409 <tcp_session_receive_message>: recv(): 25 bytes.
[OC 2023-05-01T19:48:27.180969Z] DEBUG: ipadapter.c:1051 <process_socket_read_event>: Incoming message of size 31 bytes from
[OC 2023-05-01T19:48:27.180979Z] DEBUG: ipadapter.c:1052 <process_socket_read_event>: endpoint coaps+tcp://127.0.0.1:40030
[OC 2023-05-01T19:48:27.180987Z] DEBUG: ipadapter.c:1053 <process_socket_read_event>: 
[OC 2023-05-01T19:48:27.180996Z] DEBUG: oc_network_events.c:133 <oc_network_receive_event>: inbound message(0x7fdaf0004bd0) for endpoint
[OC 2023-05-01T19:48:27.181061Z] DEBUG: tcpsession.c:493 <log_tcp_session>: found ongoing TCP session for
[OC 2023-05-01T19:48:27.181076Z] DEBUG: tcpsession.c:494 <log_tcp_session>: endpoint coaps+tcp://127.0.0.1:40030
[OC 2023-05-01T19:48:27.181085Z] DEBUG: tcpsession.c:495 <log_tcp_session>: 
[OC 2023-05-01T19:48:27.181109Z] DEBUG: ipadapter.c:1129 <process_events>: processing 1 events

main thread:
[OC 2023-05-01T19:48:27.181125Z] DEBUG: tcpsession.c:742 <free_session_async_locked>: signaled network event thread to monitor that the session needs to be removed
[OC 2023-05-01T19:48:27.181135Z] DEBUG: tcpsession.c:743 <free_session_async_locked>: free TCP session async

network thread:
[OC 2023-05-01T19:48:27.181200Z] DEBUG: tcpsession.c:290 <free_session_locked>: free TCP session(0x7fdaf0004b50, fd=20)
[OC 2023-05-01T19:48:27.181217Z] DEBUG: ipadapter.c:1013 <process_socket_signal_event>: Signal event received(fd=16, status=2)
```

The waiting inbound message is then processed by `oc_tls_recv_message` which checks if a TLS peer associated with the endpoint of the message exists, if it doesn't then it creates it.
At this moment we have a TLS peer that we wanted to close.

Proposed solution:
- add a flag to oc_endpoint_t for TCP (and DTLS?) connection to distinguish between server and client endpoints (examine the ACCEPTED flag if it can't be used)
- when an inbound message is processed by `oc_tls_recv_message` check if the receiving endpoint is flagged as a client and it that case new peer should't be opened. The message should be dropped and the event should be logged.
- examine if a similar issue cannot occur for an outbound message
- add unit tests

**Comment by jbinfn** [comment]
Hi,
Found an issue that may be related to this one. Tried to connect around 90 devices (emulated in docker containers) to a PLGD+DPS server (deployed in docker containers), at the same time, using the same docker network being used by the PLGD and DPS, all within the same machine.
Observed that few devices get onboarded and some of these, are offline in the end. This issue starts to occur with ~30 devices trying to connect at the same time. If devices are gradually connected to network, they get onboarded without issues. 
If I use a different docker bridge network to connect devices to DPS server, the issue does not occur when I connect all at the same time.
Note that this was reproduced including the integration of PLGD/DPS with our product.
