### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by LaiHuanHeng** [iotivity/iotivity-lite#45]
Is it possible to provide an Android APi that has been built?

System:Windows10

mingw32-make.exe NDK_HOME=%NDK_HOME% ANDROID_API=21 DEBUG=1 SECURE=1 IPV4=1 TCP=0 PKI=1 DYNAMIC=1
CLOUD=0 JAVA=1 IDD=1
21 was unexpected at this time.
if [ -d ../../deps/mbedtls ]; then
cd ../../deps/mbedtls &&
git clean -fdx . &&
git reset --hard &&
cd -;
fi &&
git submodule update --init &&
cd ../../deps/mbedtls &&
for patch in ../../patches/05_mbedtls_ocf-microsoft.patch ../../patches/06_mbedtls_constrained.patch ../../patches/08_mbedtls_C99.patch ../../patches/09-ocf-samsung-psk.patch ../../patches/10-ocf-samsung-anon.patch; do patch -r - -s -N -p1 < ${patch} ; done &&
echo "Patches applied in ../../deps/mbedtls/.git ../../patches/05_mbedtls_ocf-microsoft.patch ../../patches/06_mbedtls_constrained.patch ../../patches/08_mbedtls_C99.patch ../../patches/09-ocf-samsung-psk.patch ../../patches/10-ocf-samsung-anon.patch" > patched.txt
-d was unexpected at this time.
mingw32-make.exe: *** [Makefile:376: ../../deps/mbedtls/patched.txt] Error 255

**Comment by cstevens** [comment]
TODO: Try to build this using OTGC instructions as an example. Work with Kishen, then document it in a place where we can point people.

**Comment by LaiHuanHeng** [comment]
I first asked the question in otgc-android, but I haven't received any response so far. What kind of information do I need to know to build the iotivity android api?

**Comment by LaiHuanHeng** [comment]
> TODO (Clarke): Try to build this using OTGC instructions as an example. Work with Kishen, then document it in a place where we can point people.

I first asked the question in otgc-android, but I haven't received any response so far. What kind of information do I need to know to build the iotivity android api?

**Comment by LaiHuanHeng** [comment]
[There are no errors as described above in this document](https://github.com/iotivity/iotivity-lite/blob/master/port/android/README.md)
