### ISSUE TITLE
Netlink socket is not allowed on android sdk >= 30

### ISSUE THREAD

**Issue by baabel** [iotivity/iotivity-lite#475]
Running with iotivity lib on Android SDK 32:
D/tcpadapter.c <oc_tcp_connectivity_init:782>: Successfully initialized TCP adapter for device 0
**E/ipadapter.c <oc_connectivity_init:1588>: binding netlink socket 13**
I/OC-JNI: error initializing connectivity for device
    Abort.

https://android.googlesource.com/platform/system/sepolicy/+/d31936f89c49bc5c54b84bd5095f3c417da14935%5E%21/#F1

Can possibly replace netlink with ifaddrs  in ipadapter.c, don't see a notification callback, may need to poll.

https://android.googlesource.com/platform/libcore/+/refs/heads/gingerbread-release/luni/src/main/native/ifaddrs-android.h

**Comment by baabel** [comment]
Hi @Danielius1922, 

I will build iotivity-lite lib from your PR and test on android 29 & 30.

Thanks,
Brian

**Comment by baabel** [comment]
Added a few comments. Found a couple of other unrelated issues on the android build. Some of the SWIG interfaces have macro function calls, for example  OC_DBG()... but the header file that defines the macro is not #include(d) in the interface. The code still compiles, but the OC_DBG does not expand... the result is the compiler thinks OC_DBG is an actual function... the build works fine, but it defines an UNDEFINED symbol in the .so file.  The failure happens when android app does the system.loadlibrary() ... error is undefined symbol  OC_DBG.  Fix is to include the file in the swig interface file. There were a couple other situations like this, for example the assert() macro.

**Comment by Danielius1922** [comment]
> Added a few comments. Found a couple of other unrelated issues on the android build. Some of the SWIG interfaces have macro function calls, for example OC_DBG()... but the header file that defines the macro is not #include(d) in the interface. The code still compiles, but the OC_DBG does not expand... the result is the compiler thinks OC_DBG is an actual function... the build works fine, but it defines an UNDEFINED symbol in the .so file. The failure happens when android app does the system.loadlibrary() ... error is undefined symbol OC_DBG. Fix is to include the file in the swig interface file. There were a couple other situations like this, for example the assert() macro.

I recall that `OC_DBG` (and other logging macros) were moved from port/oc_log.h to port/oc_log_internal.h, seems that the swig files were not updated. I'll fix that. Same with missing assert.h include. 
It'll be nice if these kinds of problems were caught be the CI. But the builds have succeeded, but I see warnings emitted by the compiler in the jobs logs. There is no `-Werror` in the Android Makefile, let me slip that in and hopefully now the CI job will catch more problems in the Android port.

**Comment by Danielius1922** [comment]
@baabel, I've fought a bit with port yesterday, but it should be in a better shape today, could you test that branch from the PR again? 

Thank you!
D.

**Comment by Danielius1922** [comment]
Hi @baabel, I've merged the updates to master. So I'm closing this issue.

Thank you for help!
D.

**Comment by Danielius1922** [comment]
(However, I should create an implementation issue for sdk >= 30)
