### ISSUE TITLE
Possible null pointer dereference

### ISSUE THREAD

**Issue by jjmilburn** [iotivity/iotivity-lite#5]
When compiling the project with gcc 7.5 and clang `scan-build-3.9`, [line 327 in `oc_rep.c`](https://github.com/iotivity/iotivity-lite/blob/master/api/oc_rep.c#L327) indicates a possible null pointer dereference:

```
Compiling oc_rep.c...
<redacted>/oc/api/oc_rep.c:334:11: warning: Dereference of null pointer (loaded from variable 'prev')
          (*prev)->next = _alloc_rep();
          ^~~~~~~
```

**Comment by WAvdBeek** [comment]
fixed on master
