### ISSUE TITLE
Device(ESP32) resource hard to be discovered in wireless router

### ISSUE THREAD

**Issue by luoweimin-git** [iotivity/iotivity-lite#514]
Hello guys!
  when devices(esp32) connected in a router wireless LAN ,  they are very hard to discoverd each other. in other words,  oc_do_ip_discovery's callback is hard to enter.  if device1 in router wired LAN,device2 in router wireless LAN , this issue is a bit better.
just devices all connected in wired LAN, this issue will not be happen. maybe the reanson is multicast is not fit wireless env?

Looking forward to your reply! thanks!!

**Comment by Danielius1922** [comment]
This an area is out of my expertise, so I don't know what could help. @jkralik, do you have any ideas what could @luoweimin-git try or perhaps what could we change in code to help?

**Comment by jkralik** [comment]
This function  `oc_send_discovery_request` is responsible to send mcast message to network:
https://github.com/iotivity/iotivity-lite/blob/a8817c1bfc2fe831543a11af2c638b9d8fc353ba/port/esp32/adapter/src/ipadapter.c#L1055

So for debugging I recommend to put there logs and watch if any mcast message has been send through wireless.
It contains interfaces filtration so one of them can filter out the right interface. 

@luoweimin-git Do you use ipv4 or ipv6 LAN ?

**Comment by luoweimin-git** [comment]
thanks for your reply,
1 、 i use oc_do_ip_discovery(NULL, &discovery, NULL) to discover device resoure every 5 seconds ，callback function（discovery）is not easy enter（can enter， but need  lot of times）， in linux platform and  wired LAN，callback function can enter everytime and timely
2、 i use IPV4 for all demo test
3、i use  udp_multicast  example from  esp-idf  sdk （esp-idf/examples/protocols/sockets/udp_multicast/） ，two  wireless module  send and receive  multicast  pack  very  fluent, so  iotivity-lite  sdk in  esp32  platform  maybe  have some bugs?

4 、esp32 demo i  used, path is  ~/iotivity-lite/port/esp32/main/main.c

Looking forward to your reply! thanks!!

**Comment by luoweimin-git** [comment]
5、firstly i use one linux and wired device call oc_do_ip_discovery(NULL, &discovery, NULL) to discover device resoure every 5 seconds , then i use wireshark can capture wireless  coap pack, multicast addr dispaly in wireshark  is 224.0.1.187 , so this maybe can prove  that discover pack  have send to wireless  LAN,

**Comment by luoweimin-git** [comment]
thanks for your reply, problem have be fixed.  the reason is that  i disable the code about IPV6 directly in iotivity-lite/port/esp32/adapter/src/ipadapter.c , but correct way is do patch from ../../../../patches/lwip/IPV6_RECVPKTINFO.patch to esp-idf/components/lwip/lwip .  so  i guess iotivity  use IPV6 for discover device resoure firslty?

**Comment by jkralik** [comment]
Yes and you need to apply all patches ` ../../../../patches` if you want to satisfy OCF specification.

**Comment by jkralik** [comment]
Pls fill free to reopen issue if it is still valid. Thx
