### ISSUE TITLE
all ports: don't set SO_REUSEADDR for random port

### ISSUE THREAD

**Issue by jkralik** [iotivity/iotivity-lite#57]
# What
When SO_REUSEADDR is set, then multiple process of device with small chance system can peak same port for coap, coaps, coap+tcp, coaps+tcp.

# Note
For linux it is fixed by PR: https://github.com/iotivity/iotivity-lite/pull/56
For other ports it's need to be implemented too.

# Replication:
It is replicable with 1000 processes (one per device) via docker with network host  - cca 20 ports are shared among devices.

# Priority
Trivial - linux is used mainly for docker,  so for other ports it is unusual to multiple processes of devices.

**Comment by WAvdBeek** [comment]
fixed pull request #56 from iotivity/fix/sharedPort
