### ISSUE TITLE
Build error 2

### ISSUE THREAD

**Issue by LaiHuanHeng** [iotivity/iotivity-lite#59]
### Command in case of build error
> make NDK_HOME=~/android-arm-23 ANDROID_API=23 ANDROID_ABI=armeabi

> make NDK_HOME=~/android-arm-23 ANDROID_API=23 DEBUG=1 SECURE=1 IPV4=1 TCP=0 PKI=1 DYNAMIC=1 CLOUD=0 JAVA=1 IDD=1

### Error message
>ld: error: duplicate symbol: cls_ArrayList
 defined at oc_iotivity_lite_jni.h:122 (iotivity-lite-java/jni/oc_iotivity_lite_jni.h:122)
            ../port/android/arm-linux-androideabi-obj/swig/oc_api_wrap.o:(cls_ArrayList)
 defined at oc_iotivity_lite_jni.h:122 (iotivity-lite-java/jni/oc_iotivity_lite_jni.h:122)
            ../port/android/arm-linux-androideabi-obj/swig/oc_cloud_wrap.o:(.bss.cls_ArrayList+0x0)

>ld: error: duplicate symbol: cls_OCAddDeviceHandler
 defined at oc_iotivity_lite_jni.h:124 (iotivity-lite-java/jni/oc_iotivity_lite_jni.h:124)
            ../port/android/arm-linux-androideabi-obj/swig/oc_api_wrap.o:(cls_OCAddDeviceHandler)
 defined at oc_iotivity_lite_jni.h:124 (iotivity-lite-java/jni/oc_iotivity_lite_jni.h:124)
            ../port/android/arm-linux-androideabi-obj/swig/oc_cloud_wrap.o:(.bss.cls_OCAddDeviceHandler+0x0)

>ld: error: duplicate symbol: cls_OCClientResponse
 defined at oc_iotivity_lite_jni.h:125 (iotivity-lite-java/jni/oc_iotivity_lite_jni.h:125)
            ../port/android/arm-linux-androideabi-obj/swig/oc_api_wrap.o:(cls_OCClientResponse)
 defined at oc_iotivity_lite_jni.h:125 (iotivity-lite-java/jni/oc_iotivity_lite_jni.h:125)
            ../port/android/arm-linux-androideabi-obj/swig/oc_cloud_wrap.o:(.bss.cls_OCClientResponse+0x0)

>ld: error: duplicate symbol: cls_OCCloudContext
 defined at oc_iotivity_lite_jni.h:126 (iotivity-lite-java/jni/oc_iotivity_lite_jni.h:126)
            ../port/android/arm-linux-androideabi-obj/swig/oc_api_wrap.o:(cls_OCCloudContext)
 defined at oc_iotivity_lite_jni.h:126 (iotivity-lite-java/jni/oc_iotivity_lite_jni.h:126)
            ../port/android/arm-linux-androideabi-obj/swig/oc_cloud_wrap.o:(.bss.cls_OCCloudContext+0x0)

>ld: error: duplicate symbol: cls_OCCloudHandler
 defined at oc_iotivity_lite_jni.h:155 (iotivity-lite-java/jni/oc_iotivity_lite_jni.h:155)
            ../port/android/arm-linux-androideabi-obj/swig/oc_api_wrap.o:(cls_OCCloudHandler)
 defined at oc_iotivity_lite_jni.h:155 (iotivity-lite-java/jni/oc_iotivity_lite_jni.h:155)
            ../port/android/arm-linux-androideabi-obj/swig/oc_cloud_wrap.o:(.bss.cls_OCCloudHandler+0x0)

>ld: error: duplicate symbol: cls_OCConWriteHandler
 defined at oc_iotivity_lite_jni.h:127 (iotivity-lite-java/jni/oc_iotivity_lite_jni.h:127)
            ../port/android/arm-linux-androideabi-obj/swig/oc_api_wrap.o:(cls_OCConWriteHandler)
 defined at oc_iotivity_lite_jni.h:127 (iotivity-lite-java/jni/oc_iotivity_lite_jni.h:127)
            ../port/android/arm-linux-androideabi-obj/swig/oc_cloud_wrap.o:(.bss.cls_OCConWriteHandler+0x0)

>ld: error: duplicate symbol: cls_OCCoreAddDeviceHandler
 defined at oc_iotivity_lite_jni.h:145 (iotivity-lite-java/jni/oc_iotivity_lite_jni.h:145)
            ../port/android/arm-linux-androideabi-obj/swig/oc_api_wrap.o:(cls_OCCoreAddDeviceHandler)
 defined at oc_iotivity_lite_jni.h:145 (iotivity-lite-java/jni/oc_iotivity_lite_jni.h:145)
            ../port/android/arm-linux-androideabi-obj/swig/oc_cloud_wrap.o:(.bss.cls_OCCoreAddDeviceHandler+0x0)

>ld: error: duplicate symbol: cls_OCCoreInitPlatformHandler
 defined at oc_iotivity_lite_jni.h:146 (iotivity-lite-java/jni/oc_iotivity_lite_jni.h:146)
            ../port/android/arm-linux-androideabi-obj/swig/oc_api_wrap.o:(cls_OCCoreInitPlatformHandler)
 defined at oc_iotivity_lite_jni.h:146 (iotivity-lite-java/jni/oc_iotivity_lite_jni.h:146)
            ../port/android/arm-linux-androideabi-obj/swig/oc_cloud_wrap.o:(.bss.cls_OCCoreInitPlatformHandler+0x0)

>ld: error: duplicate symbol: cls_OCCreds
 defined at oc_iotivity_lite_jni.h:147 (iotivity-lite-java/jni/oc_iotivity_lite_jni.h:147)
            ../port/android/arm-linux-androideabi-obj/swig/oc_api_wrap.o:(cls_OCCreds)
 defined at oc_iotivity_lite_jni.h:147 (iotivity-lite-java/jni/oc_iotivity_lite_jni.h:147)
            ../port/android/arm-linux-androideabi-obj/swig/oc_cloud_wrap.o:(.bss.cls_OCCreds+0x0)

>ld: error: duplicate symbol: cls_OCDiscoveryAllHandler
 defined at oc_iotivity_lite_jni.h:129 (iotivity-lite-java/jni/oc_iotivity_lite_jni.h:129)
            ../port/android/arm-linux-androideabi-obj/swig/oc_api_wrap.o:(cls_OCDiscoveryAllHandler)
 defined at oc_iotivity_lite_jni.h:129 (iotivity-lite-java/jni/oc_iotivity_lite_jni.h:129)
            ../port/android/arm-linux-androideabi-obj/swig/oc_cloud_wrap.o:(.bss.cls_OCDiscoveryAllHandler+0x0)

>ld: error: duplicate symbol: cls_OCDiscoveryHandler
 defined at oc_iotivity_lite_jni.h:128 (iotivity-lite-java/jni/oc_iotivity_lite_jni.h:128)
            ../port/android/arm-linux-androideabi-obj/swig/oc_api_wrap.o:(cls_OCDiscoveryHandler)
 defined at oc_iotivity_lite_jni.h:128 (iotivity-lite-java/jni/oc_iotivity_lite_jni.h:128)
            ../port/android/arm-linux-androideabi-obj/swig/oc_cloud_wrap.o:(.bss.cls_OCDiscoveryHandler+0x0)

>ld: error: duplicate symbol: cls_OCEndpoint
 defined at oc_iotivity_lite_jni.h:148 (iotivity-lite-java/jni/oc_iotivity_lite_jni.h:148)
            ../port/android/arm-linux-androideabi-obj/swig/oc_api_wrap.o:(cls_OCEndpoint)
 defined at oc_iotivity_lite_jni.h:148 (iotivity-lite-java/jni/oc_iotivity_lite_jni.h:148)
            ../port/android/arm-linux-androideabi-obj/swig/oc_cloud_wrap.o:(.bss.cls_OCEndpoint+0x0)

>ld: error: duplicate symbol: cls_OCFactoryPresetsHandler
 defined at oc_iotivity_lite_jni.h:130 (iotivity-lite-java/jni/oc_iotivity_lite_jni.h:130)
            ../port/android/arm-linux-androideabi-obj/swig/oc_api_wrap.o:(cls_OCFactoryPresetsHandler)
 defined at oc_iotivity_lite_jni.h:130 (iotivity-lite-java/jni/oc_iotivity_lite_jni.h:130)
            ../port/android/arm-linux-androideabi-obj/swig/oc_cloud_wrap.o:(.bss.cls_OCFactoryPresetsHandler+0x0)

>ld: error: duplicate symbol: cls_OCGetPropertiesHandler
 defined at oc_iotivity_lite_jni.h:131 (iotivity-lite-java/jni/oc_iotivity_lite_jni.h:131)
            ../port/android/arm-linux-androideabi-obj/swig/oc_api_wrap.o:(cls_OCGetPropertiesHandler)
 defined at oc_iotivity_lite_jni.h:131 (iotivity-lite-java/jni/oc_iotivity_lite_jni.h:131)
            ../port/android/arm-linux-androideabi-obj/swig/oc_cloud_wrap.o:(.bss.cls_OCGetPropertiesHandler+0x0)

>ld: error: duplicate symbol: cls_OCInitPlatformHandler
 defined at oc_iotivity_lite_jni.h:132 (iotivity-lite-java/jni/oc_iotivity_lite_jni.h:132)
            ../port/android/arm-linux-androideabi-obj/swig/oc_api_wrap.o:(cls_OCInitPlatformHandler)
 defined at oc_iotivity_lite_jni.h:132 (iotivity-lite-java/jni/oc_iotivity_lite_jni.h:132)
            ../port/android/arm-linux-androideabi-obj/swig/oc_cloud_wrap.o:(.bss.cls_OCInitPlatformHandler+0x0)

>ld: error: duplicate symbol: cls_OCMainInitHandler
 defined at oc_iotivity_lite_jni.h:123 (iotivity-lite-java/jni/oc_iotivity_lite_jni.h:123)
            ../port/android/arm-linux-androideabi-obj/swig/oc_api_wrap.o:(cls_OCMainInitHandler)
 defined at oc_iotivity_lite_jni.h:123 (iotivity-lite-java/jni/oc_iotivity_lite_jni.h:123)
            ../port/android/arm-linux-androideabi-obj/swig/oc_cloud_wrap.o:(.bss.cls_OCMainInitHandler+0x0)

>ld: error: duplicate symbol: cls_OCObtAclHandler
 defined at oc_iotivity_lite_jni.h:150 (iotivity-lite-java/jni/oc_iotivity_lite_jni.h:150)
            ../port/android/arm-linux-androideabi-obj/swig/oc_api_wrap.o:(cls_OCObtAclHandler)
 defined at oc_iotivity_lite_jni.h:150 (iotivity-lite-java/jni/oc_iotivity_lite_jni.h:150)
            ../port/android/arm-linux-androideabi-obj/swig/oc_cloud_wrap.o:(.bss.cls_OCObtAclHandler+0x0)

>ld: error: duplicate symbol: cls_OCObtCredsHandler
 defined at oc_iotivity_lite_jni.h:151 (iotivity-lite-java/jni/oc_iotivity_lite_jni.h:151)
            ../port/android/arm-linux-androideabi-obj/swig/oc_api_wrap.o:(cls_OCObtCredsHandler)
 defined at oc_iotivity_lite_jni.h:151 (iotivity-lite-java/jni/oc_iotivity_lite_jni.h:151)
            ../port/android/arm-linux-androideabi-obj/swig/oc_cloud_wrap.o:(.bss.cls_OCObtCredsHandler+0x0)

>ld: error: duplicate symbol: cls_OCObtDeviceStatusHandler
 defined at oc_iotivity_lite_jni.h:153 (iotivity-lite-java/jni/oc_iotivity_lite_jni.h:153)
            ../port/android/arm-linux-androideabi-obj/swig/oc_api_wrap.o:(cls_OCObtDeviceStatusHandler)
 defined at oc_iotivity_lite_jni.h:153 (iotivity-lite-java/jni/oc_iotivity_lite_jni.h:153)
            ../port/android/arm-linux-androideabi-obj/swig/oc_cloud_wrap.o:(.bss.cls_OCObtDeviceStatusHandler+0x0)

>ld: error: duplicate symbol: cls_OCObtDiscoveryHandler
 defined at oc_iotivity_lite_jni.h:152 (iotivity-lite-java/jni/oc_iotivity_lite_jni.h:152)
            ../port/android/arm-linux-androideabi-obj/swig/oc_api_wrap.o:(cls_OCObtDiscoveryHandler)
 defined at oc_iotivity_lite_jni.h:152 (iotivity-lite-java/jni/oc_iotivity_lite_jni.h:152)
            ../port/android/arm-linux-androideabi-obj/swig/oc_cloud_wrap.o:(.bss.cls_OCObtDiscoveryHandler+0x0)

>ld: error: too many errors emitted, stopping now (use -error-limit=0 to see all errors)
clang110: error: linker command failed with exit code 1 (use -v to see invocation)
>make[1]: *** [Makefile:155：build_jni_so] error 1
make[1]: Leave directory “/home/ubuntu64/Word/project/iotivity-lite/swig”
make: *** [Makefile:368：swig] error 2

**Comment by LaiHuanHeng** [comment]
![1653548447(1)](https://user-images.githubusercontent.com/16424138/170436073-67815d8a-40a7-48c9-92f7-818e41c80b1a.png)

**Comment by Danielius1922** [comment]
@LaiHuanHeng I think this should be fixed, reopen if the issue still occurs.
