### ISSUE TITLE
Syntax error - possibly a missing semicolon.

### ISSUE THREAD

**Issue by foadmoradi** [iotivity/iotivity-lite#621]
Dear friends, I need your help to resolve the following issue.

I am compiling android version in the path /port/android/. I use openjdk version "1.8.0_362", javac 1.8.0_362, the command:

make NDK_HOME=~/android-arm-23 ANDROID_API=23

It goes well until reaching he following error, related to swig section.

Error is as follows:

make -C ../../swig
make[1]: Entering directory '/home/foadmoradi/iotivity-lite/swig'
rm -f iotivity-lite-java/libs/iotivity-lite.jar
rm -f iotivity-lite-java/libs/libiotivity-lite-jni.so
rm -f iotivity-lite-java/jni/*.c
rm -f iotivity-lite-java/jni/*.h
rm -f iotivity-lite-java/src/org/iotivity/*.java
rm -rf iotivity-lite-java/src/org/iotivity/oc
rm -rf iotivity-lite-java/bin/
rm -rf  ../port/android/arm-linux-androideabi-obj/swig/

#delete so and jar files copied to samples

rm -f apps/android_simple_client/SimpleClient/app/src/main/jniLibs//libiotivity-lite-jni.so
rm -f apps/android_simple_client/SimpleClient/app/libs/iotivity-lite.jar
rm -f apps/android_simple_server/SimpleServer/app/src/main/jniLibs//libiotivity-lite-jni.so
rm -f apps/android_simple_server/SimpleServer/app/libs/iotivity-lite.jar
rm -f apps/android_on_boarding_tool/OnBoardingTool/app/src/main/jniLibs//libiotivity-lite-jni.so
rm -f apps/android_on_boarding_tool/OnBoardingTool/app/libs/iotivity-lite.jar
rm -f apps/oc/android_simple_client/SimpleClient/app/src/main/jniLibs//libiotivity-lite-jni.so
rm -f apps/oc/android_simple_client/SimpleClient/app/libs/iotivity-lite.jar
rm -f apps/oc/android_simple_server/SimpleServer/app/src/main/jniLibs//libiotivity-lite-jni.so
rm -f apps/oc/android_simple_server/SimpleServer/app/libs/iotivity-lite.jar
rm -f apps/oc/android_multi_device_client/MultiDeviceClient/app/src/main/jniLibs//libiotivity-lite-jni.so
rm -f apps/oc/android_multi_device_client/MultiDeviceClient/app/libs/iotivity-lite.jar
rm -f apps/oc/android_multi_device_server/MultiDeviceServer/app/src/main/jniLibs//libiotivity-lite-jni.so
rm -f apps/oc/android_multi_device_server/MultiDeviceServer/app/libs/iotivity-lite.jar
rm -f apps/oc/android_on_boarding_tool/OnBoardingTool/app/src/main/jniLibs//libiotivity-lite-jni.so
rm -f apps/oc/android_on_boarding_tool/OnBoardingTool/app/libs/iotivity-lite.jar
swig -java -package org.iotivity -outdir iotivity-lite-java/src/org/iotivity/ -DOC_CLIENT -DOC_SERVER -DOC_CLOUD -DOC_SECURITY -DOC_IDD_API -DOC_PKI -DOC_TCP -D__linux__ -I../ -I../include -I../port -I../util/ -I../deps/tinycbor/src/ -I../security -I../cloud -I../port/android -o iotivity-lite-java/jni/oc_api_wrap.c swig_interfaces/oc_api.i
../include/oc_uuid.h:122: Error: Syntax error - possibly a missing semicolon.
Makefile:159: recipe for target 'oc_api.i' failed
make[1]: *** [oc_api.i] Error 1
make[1]: Leaving directory '/home/foadmoradi/iotivity-lite/swig'
Makefile:417: recipe for target 'swig' failed
make: *** [swig] Error 2

![git_help](https://github.com/iotivity/iotivity-lite/assets/16817856/b45dcd64-ddcb-47fd-b74c-b45681264d65)

**Comment by Danielius1922** [comment]
@foadmoradi Ah sorry, I somehow missed this totally. Is this still an issue? The swig interfaces are built with every PR to master, and the builds are succeeding, so we might have some building setup issue if it's still failing for you. Are you using master?

**Comment by Danielius1922** [comment]
No response, please reopen if this is still an issue.
