### ISSUE TITLE
How to make cloud de-register operation in server_certification_tests.c ? 

### ISSUE THREAD

**Issue by Trishia** [iotivity/iotivity-lite#67]
@kmaloor 

I'm wondering how to make cloud de-register operation in [server_certification_tests.c](https://github.com/iotivity/iotivity-lite/blob/master/apps/server_certification_tests.c). 

Cloud Register, Cloud Login, Cloud Logout, Cloud Refresh Token, Publish Resources operations work well but Cloud DeRegister only shows "Could not issue Cloud Register request" at any situation.  

How can I do that operation successfully? 
Inform me your guide to do this. 
 
Thanks in advance.

**Comment by Trishia** [comment]
@kmaloor 
I have known that device reset also calls oc_cloud_deregister() internally. I used to witness deregister event on the cloud when resetting device by obt a few months ago. 

What is the cause of this problem ?  This [commit](https://github.com/iotivity/iotivity-lite/commit/60138901935d4832599a1ead6486c152bc1a68d0#diff-8feb5153f556c5f1efac98606a0bf77d2c4367f7708f38186088d3b69ff49a52) of oc_cloud_apis.c can be affect on this problem ??

**Comment by Trishia** [comment]
@kmaloor 

I found error message caused by oc_do_delete() in cloud_access_deregister() of oc_cloud_apis.c like below : 

The error message shows that "Serialized header length 1051 exceeds COAP_MAX_HEADER_SIZE 181-TCP" because delete query uri including access token, uid, di is too long I guess. 
How can we handle this coap limitation ? 
```
DEBUG: ../../security/oc_pstat.c <dump_pstat_dos:98>: oc_pstat: dos is RFNOP
DEBUG: ../../messaging/coap/transactions.c <coap_new_transaction:91>: Created new transaction 13159: 0xdead38
DEBUG: ../../messaging/coap/coap.c <coap_serialize_options:397>: Calculating size of options
DEBUG: ../../messaging/coap/coap.c <coap_tcp_compute_message_length:969>: -TCP Len < COAP_TCP_EXTENDED_LENGTH_3_DEFAULT_LEN(65805) 
DEBUG: ../../messaging/coap/coap.c <coap_tcp_compute_message_length:980>: -Size of options : 1039 Total length of CoAP_TCP message (Options+Payload) : 1039 
DEBUG: ../../messaging/coap/coap.c <coap_tcp_compute_message_length:982>: -COAP_TCP header len field : 14 Extended length : 770 
ERROR: ../../messaging/coap/coap.c <coap_oscore_serialize_message:1131>: Serialized header length 1051 exceeds COAP_MAX_HEADER_SIZE 181-TCP
DEBUG: ../../messaging/coap/transactions.c <coap_clear_transaction:200>: Freeing transaction 13159: 0xdead38
```

**Comment by Trishia** [comment]
@kmaloor 

It has logical problem of calculating tpc coap header size which has long option size because of long query uri including accesstoken.

In the code https://github.com/iotivity/iotivity-lite/blob/master/messaging/coap/coap.c#L1104, https://github.com/iotivity/iotivity-lite/blob/master/messaging/coap/coap.c#L1128, https://github.com/iotivity/iotivity-lite/blob/master/messaging/coap/coap.c#L1186, https://github.com/iotivity/iotivity-lite/blob/master/messaging/coap/coap.c#L1189, https://github.com/iotivity/iotivity-lite/blob/master/messaging/coap/coap.c#L1200 of coap_oscore_serialize_message(), there should be modification to solve this issue. These calculating and checking codes are affected on sending DELETE tcp coap message including long option.
 
After removing checking code with COAP_MAX_HEADER_SIZE, DELETE message of /oic/sec/account works fine when reseting operation.

Could you fix this issue ?

**Comment by jkralik** [comment]
By RFC of coap the max size of OPTION Uri-Query is 255 bytes https://datatracker.ietf.org/doc/html/rfc7252/#section-5.10 so the maximum size of the token can be 243bytes.  ( len("accesstoken=")=12 + len(token)244bytes".

So you cannot push JWT token as a query parameter - you need to split it into more query options but this is not supported by OCF spec now. We extended OCF spec that the device can make signIn before he did signOff - in this case, device doesn't need to provide an access token as a query(OPTION) parameter.

**Comment by Trishia** [comment]
@jkralik @ondrejtomcik  @marktrayer 
I have got the CRs (i.e. CR3298, CR3299) related to this issues from Mitch. De-registering without accesstoken can solve this issue about option uri-query length and any other problems as well. For now the only way to do de-registering of iotivity-lite device does not work. Do I have to remove accesstoken in Uri-Query of oc_cloud_deregister() ? or wait to be fixed by someone with confirmed CRs ?

**Comment by Trishia** [comment]
Regarding the implementation about Delete /oic/sec/account without access token issue, the jakarta branch of iotivity-lite has implemented it so the issue of limited option size for uri query in coap message was solved. And plgd cloud can accept this message without access token as described in https://github.com/plgd-dev/cloud/issues/360.
