### ISSUE TITLE
Iotivity client doesn't rediscover resources after some time

### ISSUE THREAD

**Issue by ihebmedd** [iotivity/iotivity-lite#9]
I'm running an IoTivity client that rediscovers available resources every 20 seconds. At the start it works fine. However, after around 2 and a half minutes the client doesn't discover the resource anymore. When I restart the client it still doesn't find it but when I restart the server the client rediscover it but for 2:30 min. Why is this happening and how can I fix it? I used IoTivity 1.2.1 and I'm running the server and the client on different embedded devices (connected to the same network but on different switch). I also tried IoTivity lite and I still got the same issue.

**Comment by WAvdBeek** [comment]
IoTivity 1.2.1 is no longer maintained.
This repo and issues are for IoTivity-Lite
